# Generated by Django 5.1.4 on 2024-12-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='events/')),
                ('highlights', models.TextField(blank=True, help_text='Comma-separated highlights of the event.')),
            ],
        ),
    ]
